config/routes.rb
Rails.application.routes.draw do
  
  get "checks/create"    => "checks#create"
  post "checks/create"    => "checks#create"
  
  resources :users, only: [:new, :create]
  resources :user_sessions, only: [:create, :destroy]
  
  delete '/sign_out', to: 'user_sessions#destroy', as: :sign_out
  get '/sign_in', to: 'user_sessions#new', as: :sign_in
  get '/sign_up', to: 'users#new', as: :sign_up
  
  root 'checks#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/check.rb
class Check < ApplicationRecord
  validates :method, :text, presence: true
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
validates :email, :password, presence: true
has_many :checks
acts_as_authentic do |c|
    c.crypto_provider = Authlogic::CryptoProviders::Sha512
end
end

app/models/user_session.rb
class UserSession < Authlogic::Session::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
private

def current_user_session
  return @current_user_session if defined?(@current_user_session)
  @current_user_session = UserSession.find
end

def current_user
  return @current_user if defined?(@current_user)
  @current_user = current_user_session && current_user_session.user
end

def user_already_authorized
  if current_user
    redirect_to root_path
  end
end

def user_not_unauthorized
  if !current_user
    redirect_to sign_in_path
  end
end

helper_method :current_user_session, :current_user
end

app/controllers/checks_controller.rb
class ChecksController < ApplicationController
  skip_before_action :verify_authenticity_token
  before_action :user_not_unauthorized

  def index
    @data = @current_user.checks
  end

  def create
    @data = Check.new(data_params)
    @data[:result] = case @data[:method]
                     when "palindrome"
                       @data[:text].palindrome?
                     when "brackets"
                       @data[:text].valid_brackets?
                     end
    @data[:user_id] = @current_user.id
    @data.save
  end

  private
    def data_params
      params.permit(:method, :text, :token)
    end
	
end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController
  def new
    user_already_authorized
    @user_session = UserSession.new
  end

  def create
    @user_session = UserSession.new(user_session_params.to_h)
     if @user_session.save
	   redirect_to root_path
     else
       render :new
     end
  end

  def destroy
    current_user_session.destroy
    redirect_to root_path
  end

  private

  def user_session_params
    params.require(:user_session).permit(:email, :password, :remember_me)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    user_already_authorized
    @user = User.new
  end

  def create
    @user = User.new(users_params)
	if !check_exist && @user.save
	  redirect_to root_path
	else
	  render :new
	end
  end

  private
  
  def check_exist
    User.exists?(email: @user[:email])
  end
  
  def users_params
    params.require(:user).permit(:email, :password)
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/checks_helper.rb
module ChecksHelper
end

app/views/checks/create.html.erb
<form action = "/checks/create" method="post">
  <p>
    <h2>Выберите метод проверки</h2>
    <input type="radio" id="palindrome" name="method" value="palindrome">
    <label for="palindrome">Палиндром</label>
    <input type="radio" id="brackets" name="method" value="brackets">
    <label for="brackets">Скобки</label>
  </p>
  <p>
    <h2>Введите текст</h2>
    <input type="text" name="text">
  </p>
  <input type="submit"/>
</form>

<% if !@data[:result].nil?%>
  <h2>Ответ:
    <%= case @data[:result]
          when true
            "да"
          when false
            "нет"
        end %>
   </h2>
<% end %><br>
<%= link_to 'Таблица запросов', root_path %> ..
<%= link_to 'Выйти', sign_out_path, method: :delete %>

app/views/checks/index.html.erb
<h1>Listing checks</h1>

<table border="1" style="width: 70%;">
  <tr>
    <th>id</th>
    <th>Method</th>
    <th>Text</th>
    <th>Result</th>
  </tr>

  <% @data.each do |data| %>
    <tr style="text-align:center">
      <td><%= data.id %></td>
      <td><%= data.method %></td>
      <td><%= data.text %></td>
      <td><%= data.result %></td>
    </tr>
  <% end %>
</table>

<br>
<%= link_to 'Новая запись', checks_create_path %> ..
<%= link_to 'Выйти', sign_out_path, method: :delete %>

app/views/checks/new.html.erb
<form action = "/checks/new" method="post">
  <p>
    <h2>Выберите метод проверки</h2>
    <input type="radio" id="palindrome" name="method" value="palindrome">
    <label for="palindrome">Палиндром</label>
    <input type="radio" id="brackets" name="method" value="brackets">
    <label for="brackets">Скобки</label>
  </p>
  <p>
    <h2>Введите текст</h2>
    <input type="text" name="text">
  </p>
  <input type="submit"/>
</form>

<% if !@data[:result].nil?%>
  <h2>Ответ:
    <%= case @data[:result]
          when true
            "да"
          when false
            "нет"
        end %>
   </h2>
<% end %>
<br><%= link_to 'Таблица запросов', root_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/shared/_errors.html.erb
<% if object.errors.any? %>
  <div class="panel panel-warning errors">
    <div class="panel-heading">
      <h5><i class="glyphicon glyphicon-exclamation-sign"></i> Found errors while saving</h5>
    </div>

    <ul class="panel-body">
      <% object.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/authorized.html.erb
<h1>Авторизация</h1>

<p>Вы уже авторизованы!</p>
<%= link_to 'Выйти', sign_out_path, method: :delete %>

app/views/shared/unauthorized.html.erb
<center>
  <h1>Добро пожаловать!</h1>
  <p>Только зарегистрированные пользователи могут что-то там делать.</p>
  <p>Пожалуйста, зарегистрируйтесь, или войдите под своей учётной записью.</p>
  <p>
    <%= link_to 'Регистрация', new_user_path %> ..
    <%= link_to 'Вход', sign_in_path %>
  </p>
</center>

app/views/user_sessions/new.html.erb
<div class="page-header">

<h1>Авторизация</h1></div>

<%= form_for @user_session do |f| %>
  <%= render 'shared/errors', object: @user_session %>

  <div class="form-group">
    <%= f.label :email %>
    <%= f.email_field :email, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :password %>
    <%= f.password_field :password, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :remember_me %>
    <%= f.check_box :remember_me %>
  </div>

  <%= f.submit 'Войти' %>
<% end %>
<br>
<%= link_to 'Зарегистрироваться', sign_up_url %>

app/views/users/new.html.erb
<div class="page-header">

<h1>Регистрация</h1></div>

<%= form_for @user do |f| %>
  <%= render 'shared/errors', object: @user %>

  <div class="form-group">
    <%= f.label :email %>
    <%= f.email_field :email, class: 'form-control' %>
  </div>
  
  <div class="form-group">
    <%= f.label :password %>
    <%= f.password_field :password, class: 'form-control' %>
  </div>

  <%= f.submit 'Зарегистрироваться' %>

<% end %>
<br>
<%= link_to 'Войти', sign_in_url %>